apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
  name: pre-topic-model
  namespace: streaming
spec:
  schedule: "0 1 * * *"
  concurrencyPolicy: Forbid
  template:
    type: Python
    pythonVersion: "3"
    mode: cluster
    image: "gcr.io/distributed-email-pipeline/email_stream_processor:latest"
    imagePullPolicy: Always
    mainApplicationFile: /app/src/email_stream_processor/jobs/topic_model_preprocessing.py
    sparkConf:
        "spark.dynamicAllocation.maxExecutors": "8"
        "spark.kubernetes.authenticate.driver.serviceAccountName": "streaming"
        "spark.kubernetes.container.image": "gcr.io/distributed-email-pipeline/email_stream_processor:latest"
        "spark.kubernetes.namespace": "streaming"
        "spark.kubernetes.driver.secrets.service-account": "/etc/secrets"
        "spark.kubernetes.executor.secrets.service-account": "/etc/secrets"
        "spark.kubernetes.executorEnv.BUCKET_PARQUET": "gs://distributed-email-pipeline-parquet/email_parquet/"
        "spark.kubernetes.executorEnv.GOOGLE_APPLICATION_CREDENTIALS": "/etc/secrets/gcp_service_account.json"
        "spark.kubernetes.driverEnv.BUCKET_PARQUET": "gs://distributed-email-pipeline-parquet/email_parquet/"
        "spark.kubernetes.driverEnv.GOOGLE_APPLICATION_CREDENTIALS": "/etc/secrets/gcp_service_account.json"
        "spark.hadoop.fs.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
        "spark.hadoop.fs.AbstractFileSystem.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS"
        "spark.hadoop.fs.gs.project.id": "distributed-email-pipeline"
        "spark.hadoop.fs.gs.auth.service.account.enable": "true"
        "spark.hadoop.fs.gs.auth.service.account.json.keyfile": "/etc/secrets/gcp_service_account.json"
    sparkVersion: "2.4.5"
    deps:
      jars:
        - local:///app/jars/spark-sql-kafka-0-10_2.11-2.4.5.jar
        - local:///app/jars/kafka-clients-2.4.1.jar
        - local:///app/jars/gcs-connector-hadoop2-2.0.1-shaded.jar
    restartPolicy:
      type: Always
      onFailureRetries: 3
      onFailureRetryInterval: 10
      onSubmissionFailureRetries: 5
      onSubmissionFailureRetryInterval: 20
    driver:
      coreRequest: "0.5"
      memory: "2G"
      labels:
        version: 2.4.5
      serviceAccount: streaming
    executor:
      instances: 1
      coreRequest: "1.5"
      memory: "8G"
      labels:
        version: 2.4.5
