apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: email-stream-processor
  namespace: streaming
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "gcr.io/distributed-email-pipeline/email_stream_processor:latest"
  imagePullPolicy: Always
  mainApplicationFile: /app/src/email_stream_processor/jobs/stream_pipeline.py
  sparkConf:
      "spark.kubernetes.authenticate.driver.serviceAccountName": "streaming"
      "spark.kubernetes.container.image": "gcr.io/distributed-email-pipeline/email_stream_processor:latest"
      "spark.kubernetes.namespace": "streaming"
      "spark.kubernetes.driver.secretKeyRef.KAFKA_HOSTS": "kafka-secret:hosts"
      "spark.kubernetes.executor.secretKeyRef.KAFKA_HOSTS": "kafka-secret:hosts"
      "spark.kubernetes.driver.secrets.service-account": "/etc/secrets"
      "spark.kubernetes.executor.secrets.service-account": "/etc/secrets"
      "spark.kubernetes.executorEnv.KAFKA_TOPIC": "email"
      "spark.kubernetes.executorEnv.BUCKET_PARQUET": "gs://distributed-email-pipeline-parquet/email_parquet/"
      "spark.kubernetes.executorEnv.BUCKET_CHECKPOINT": "gs://distributed-email-pipeline-checkpoint/checkpoint/"
      "spark.kubernetes.driverEnv.KAFKA_TOPIC": "email"
      "spark.kubernetes.driverEnv.BUCKET_PARQUET": "gs://distributed-email-pipeline-parquet/email_parquet/"
      "spark.kubernetes.driverEnv.BUCKET_CHECKPOINT": "gs://distributed-email-pipeline-checkpoint/checkpoint/"
      "spark.hadoop.fs.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
      "spark.hadoop.fs.AbstractFileSystem.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS"
      "spark.hadoop.fs.gs.project.id": "distributed-email-pipeline"
      "spark.hadoop.fs.gs.auth.service.account.enable": "true"
      "spark.hadoop.fs.gs.auth.service.account.json.keyfile": "/etc/secrets/gcp_service_account.json"
  sparkVersion: "2.4.5"
  deps:
    jars:
      - https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.11/2.4.5/spark-sql-kafka-0-10_2.11-2.4.5.jar
      - https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.4.1/kafka-clients-2.4.1.jar
      - https://repo1.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/hadoop2-2.0.1/gcs-connector-hadoop2-2.0.1-shaded.jar
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    labels:
      version: 2.4.5
    serviceAccount: streaming
  executor:
    instances: 2
    labels:
      version: 2.4.5
